/** Declaration file generated by dts-gen */

import type { Widgets as W } from 'blessed';

interface NewBorder extends Omit<W.Border, 'bg' | 'fg'> {
        /**
         * Border foreground and background, must be numbers (-1 for default).
         */
        bg?: number | string;
        fg?: number | string;
    
}

class NewLog extends W.Log {
    log(text: string, ...any: unknown[]): void;
}


declare module 'blessed' {

    namespace Widgets {

        interface LogOptions extends W.LogOptions {
            label?: string | LabelOptions;
        }

        interface BoxOptions extends W.BoxOptions {
            border?: NewBorder | "line" | "bg" | undefined;
        }

    }

    export function log(options?: Widgets.LogOptions): NewLog;
}

